import {test,expect} from '@playwright/test';
test('検索・詳細・保存・決済失敗・成功・ダウンロード・リセット',async({page})=>{
 await page.goto('/');
 await expect(page.getByRole('heading',{name:'アイデアを、'})).toBeVisible();
 await page.getByRole('searchbox',{name:'資料を検索'}).fill('企画提案');
 await expect(page.locator('.card')).toHaveCount(1);
 await page.getByRole('heading',{name:'企画提案スライド'}).getByRole('link').click();
 await expect(page.getByRole('heading',{name:'収録内容'})).toBeVisible();
 await page.getByRole('button',{name:'カートに追加する'}).click();
 await expect(page.getByRole('button',{name:'カートに追加済み'})).toBeDisabled();
 await page.reload();
 await page.getByRole('link',{name:'カートを見る'}).click();
 await expect(page.locator('.total')).toContainText('¥1,200');
 await page.getByRole('link',{name:'デモ購入へ進む'}).click();
 await page.getByRole('radio',{name:'失敗を試す'}).check();
 await page.getByRole('checkbox',{name:'利用規約・利用許諾'}).check();
 await page.getByRole('button',{name:'デモ購入を確定する'}).click();
 await expect(page.getByRole('alert')).toContainText('失敗');
 await expect(page.locator('.cart-row')).toHaveCount(1);
 await page.getByRole('radio',{name:'成功',exact:true}).check();
 await page.getByRole('button',{name:'デモ購入を確定する'}).click();
 await expect(page.getByRole('heading',{name:'デモ購入が完了しました。'})).toBeVisible();
 const promise=page.waitForEvent('download');
 await page.getByRole('link',{name:'ダウンロード ↓'}).click();
 const download=await promise;
 expect(download.suggestedFilename()).toBe('企画提案スライド.pptx');
 expect(await download.failure()).toBeNull();
 await page.reload();
 await expect(page.getByRole('link',{name:'ダウンロード ↓'})).toBeVisible();
 const popup=page.waitForEvent('popup');await page.getByRole('link',{name:'模擬領収書を表示・印刷'}).click();const receipt=await popup;await expect(receipt.getByRole('heading',{name:'模擬領収書',exact:true})).toBeVisible();await expect(receipt.locator('body')).toContainText('実入金なし');expect(await receipt.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await receipt.close();
 const receiptDownload=page.waitForEvent('download');await page.getByRole('link',{name:'HTMLを保存',exact:true}).click();expect((await receiptDownload).suggestedFilename()).toBe('demo-receipt.html');
 await page.getByText('購入時に同意した利用規約・返金条件',{exact:true}).click();await expect(page.locator('details')).toContainText('local-2026-10-01');
 await page.goto('/');await page.getByRole('link',{name:'購入済み・再取得',exact:true}).click();await expect(page.getByRole('link',{name:'ダウンロード ↓'})).toBeVisible();
 await page.getByRole('link',{name:'カート 0'}).click();
 await expect(page.getByRole('heading',{name:'カートは空です'})).toBeVisible();
 await page.goto('/#guide');
 page.once('dialog',d=>d.accept());
 await page.getByRole('button',{name:'デモデータをリセット'}).click();
 await page.getByRole('link',{name:'デモ注文履歴を見る'}).click();
 await expect(page.getByRole('heading',{name:'デモ注文はまだありません'})).toBeVisible();
});
test('カテゴリ・空検索・合計・削除・空決済・キーボード・画面幅',async({page})=>{
 await page.goto('/');
 await page.getByRole('button',{name:'教育・研修',exact:true}).click();
 await expect(page.locator('.card')).toHaveCount(1);
 await page.getByRole('searchbox',{name:'資料を検索'}).fill('見つからない商品');
 await expect(page.getByRole('heading',{name:'該当する資料がありません'})).toBeVisible();
 await page.getByRole('button',{name:'条件をリセット'}).click();
 await expect(page.locator('.card')).toHaveCount(6);
 await page.getByRole('button',{name:'企画提案スライドをカートに追加',exact:true}).click();
 await page.getByRole('button',{name:'営業提案スライドをカートに追加',exact:true}).click();
 await page.getByRole('link',{name:'カート 2'}).click();
 await expect(page.locator('.total')).toContainText('¥2,700');
 await page.getByRole('button',{name:'企画提案スライドを削除',exact:true}).click();
 await expect(page.locator('.total')).toContainText('¥1,500');
 await page.getByRole('button',{name:'営業提案スライドを削除',exact:true}).click();
 await page.goto('/#checkout');
 await expect(page.getByRole('heading',{name:'カートは空です'})).toBeVisible();
 await expect(page.getByRole('button',{name:'デモ購入を確定する'})).toHaveCount(0);
 await page.goto('/');
 await page.reload();
 await expect(page.locator('.card')).toHaveCount(6);
 await page.keyboard.press('Tab');
 await expect(page.getByRole('link',{name:'本文へ移動'})).toBeFocused();
 await page.keyboard.press('Enter');
 await expect(page.locator('main')).toBeFocused();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('不正な保存データでも起動する',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('slide-market-demo-v1','{"cart":["invalid",null,"proposal","proposal"],"orders":[null,{"id":"bad","items":["invalid"]}]}'));
 await page.goto('/#cart');await expect(page.locator('.cart-row')).toHaveCount(1);
});
