const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const yen=n=>'¥'+n.toLocaleString('ja-JP');
export function receiptSnapshot(quote,selected,date,id){
 const tax=Math.floor(quote.total/11); // 税込10%を仮定する学習用。実販売の税処理ではない。
 return {version:'demo-receipt-v1',number:`LOCAL-${id}`,issuedAt:date,issuer:'Slide Market（学習用デモ）',currency:'JPY',items:selected.map(p=>({id:p.id,name:p.name,quantity:1,amount:p.price})),subtotal:quote.subtotal,discount:quote.discount,total:quote.total,taxModel:'demo-inclusive-10-percent',taxRate:10,tax,net:quote.total-tax};
}
export function receiptHtml(order){
 const r=order.receiptSnapshot;if(!r)throw new Error('購入時の領収書データがない注文です。');
 return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>模擬領収書 ${escape(r.number)}</title><style>body{font-family:system-ui,sans-serif;max-width:800px;margin:32px auto;padding:0 20px;color:#203047;line-height:1.6}h1{font-size:28px}.notice{border:2px solid #b45309;padding:14px;background:#fff7ed;font-weight:600}table{border-collapse:collapse;width:100%;margin:24px 0}th,td{border-bottom:1px solid #cbd5e1;padding:12px;text-align:left;overflow-wrap:anywhere}td:last-child,th:last-child{text-align:right}dl{display:grid;grid-template-columns:1fr 1fr;gap:10px}dd{text-align:right;margin:0}.id{overflow-wrap:anywhere}.total{font-size:22px;font-weight:bold}@media(max-width:480px){body{margin:12px auto;padding:0 12px}th,td{padding:8px}}@media print{body{margin:0;max-width:none}.print-help{display:none}.notice{background:white}table,dl{break-inside:avoid}}</style></head><body><h1>模擬領収書</h1><p class="notice">学習用・実入金なし。支払いの証明・適格請求書・経費精算には使用できません。</p>${order.status==='refunded'?'<p class="notice">この注文は全額模擬返金済みです。下記は購入時の記録です。</p>':''}<p>${escape(r.issuer)}</p><p class="id">領収書番号：${escape(r.number)}<br>注文番号：${escape(order.id)}<br>発行日時：${escape(new Date(r.issuedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}))}（日本時間）</p><table><thead><tr><th>購入商品・セット</th><th>数量</th><th>模擬税込価格</th></tr></thead><tbody>${r.items.map(i=>`<tr><td>${escape(i.name)}</td><td>${i.quantity}</td><td>${yen(i.amount)}</td></tr>`).join('')}</tbody></table><dl><dt>小計</dt><dd>${yen(r.subtotal)}</dd><dt>クーポン割引</dt><dd>−${yen(r.discount)}</dd><dt class="total">模擬合計（税込）</dt><dd class="total">${yen(r.total)}</dd><dt>仮の税抜金額</dt><dd>${yen(r.net)}</dd><dt>仮の消費税（10%）</dt><dd>${yen(r.tax)}</dd></dl><p>税額は割引後の模擬合計から10/110を計算し、円未満を切り捨てています。全商品を仮の10%対象とする学習用の計算です。実販売の税区分、登録番号、販売者情報は未設定です。</p><p>宛名・住所・カード情報は収集しません。購入時の名称・金額を保存したデータから表示しています。</p><p class="print-help">ブラウザの印刷機能で印刷・PDF保存できます（Ctrl+P／⌘P）。</p></body></html>`;
}
