import {useEffect,useState} from 'react';
import {api} from './api';
type State={enabled:boolean;recoveryCodesRemaining:number};
export function AdminSecurity(){
 const [status,setStatus]=useState<State|null>(null),[pending,setPending]=useState<{secret:string;uri:string}|null>(null),[codes,setCodes]=useState<string[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const reload=async()=>setStatus(await api('/api/admin/security/status'));
 useEffect(()=>{reload().catch(e=>setError(e.message));},[]);
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="guide"><h2>管理者の認証設定</h2>{error&&<p role="alert" className="alert">{error}</p>}{notice&&<p role="status" className="toast">{notice}</p>}<p>MFA：{status?.enabled?'有効':'未設定'} ／ 未使用の復旧コード：{status?.recoveryCodesRemaining??0}件</p><p>外部サービスへの登録は不要です。TOTP対応のオフライン認証アプリへ設定できます。同じ端末のCLIでコードを生成する方法は、ローカルの動作確認用です。</p>
 {!status?.enabled&&!pending&&<form className="stack compact" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void action(async()=>{setPending(await api('/api/admin/security/mfa/setup','POST',{password:d.get('password')}));});}}><label>設定用の管理パスワード<input name="password" type="password" autoComplete="current-password" required/></label><button className="button" disabled={busy}>MFA設定を開始</button></form>}
 {pending&&<form className="stack" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void action(async()=>{const r=await api<{recoveryCodes:string[]}>('/api/admin/security/mfa/confirm','POST',{code:d.get('code')});setCodes(r.recoveryCodes);setPending(null);await reload();setNotice('MFAを有効にしました。復旧コードを安全に保存してください。');});}}><p>次の秘密キーを認証アプリに登録してください。設定は5分で失効します。</p><label>認証アプリ用秘密キー<input readOnly value={pending.secret}/></label><label>登録URI<textarea readOnly value={pending.uri} rows={3}/></label><p>CLIで確認する場合：<code>npm run admin:otp</code>（商品管理者は末尾に <code>-- editor</code>）。設定中のコードは同じブラウザから開始した最新の設定を使用します。</p><label>設定確認コード<input name="code" required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code"/></label><button className="button" disabled={busy}>コードを確認してMFAを有効化</button></form>}
 {codes.length>0&&<div className="panel"><h3>復旧コード（この画面でのみ表示）</h3><p>1回ずつ使用できます。パスワードも必要です。</p><pre>{codes.join('\n')}</pre><button onClick={()=>setCodes([])}>保存したので閉じる</button></div>}
 {status?.enabled&&<form className="stack compact" onSubmit={e=>{e.preventDefault();if(!window.confirm('MFAを解除しますか？'))return;const d=new FormData(e.currentTarget);void action(async()=>{await api('/api/admin/security/mfa/disable','POST',Object.fromEntries(d));setCodes([]);await reload();setNotice('MFAを解除しました。');});}}><label>MFA解除用パスワード<input name="password" type="password" required autoComplete="current-password"/></label><label>新しい認証コードまたは復旧コード<input name="code" required autoComplete="one-time-code" maxLength={30}/></label><button disabled={busy}>MFAを解除する</button></form>}
 <p>コードは30秒ごとに変わり、一度使ったコードは再使用できません。返金前の再認証でも新しいコードを入力してください。紛失時はサーバーを停止して <code>npm run admin:reset</code> でパスワードとMFAを初期化できます。</p></div>;
}
