import {useEffect,useState} from 'react';
import {api, type Product,type Order,type Session,type Page} from './api';
import {AdminSecurity} from './AdminSecurity';
const yen=(n:number)=>`¥${n.toLocaleString('ja-JP')}`;
type Legal={title:string;body:string[]};
export function LegalPage({kind}:{kind:string}){const [pages,setPages]=useState<Record<string,Legal>>({}),[error,setError]=useState('');useEffect(()=>{api<{pages:Record<string,Legal>}>('/api/legal').then(r=>setPages(r.pages)).catch(e=>setError(e.message));},[]);const page=pages[kind];return <section className="inner guide"><h1>{page?.title||'販売条件を読み込み中'}</h1>{error&&<p role="alert" className="alert">{error}</p>}{page?.body.map(t=><p key={t}>{t}</p>)}<p>規約バージョン：local-2026-10-01</p></section>;}
export function ContactPage(){const [error,setError]=useState(''),[receipt,setReceipt]=useState(''),[busy,setBusy]=useState(false);
 return <section className="inner guide"><h1>お問い合わせ</h1><p>ローカルに保存し、管理画面で確認します。外部メールは送信しません。架空のメールを使用してください。</p>{error&&<p role="alert" className="alert">{error}</p>}{receipt?<p role="status" className="toast">受付番号：{receipt}</p>:<form className="stack" onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget);setBusy(true);setError('');try{const r=await api<{id:string}>('/api/inquiries','POST',Object.fromEntries(d));setReceipt(r.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>メール<input name="email" type="email" required maxLength={254}/></label><label>カテゴリ<select name="category"><option value="download">ダウンロード</option><option value="product">商品について</option><option value="other">その他</option></select></label><label>注文番号（任意）<input name="orderId" maxLength={100}/></label><label>お問い合わせ内容<textarea name="body" required maxLength={4000} rows={6}/></label><button className="button" disabled={busy}>問い合わせを保存する</button></form>}</section>;
}
type Notification={id:string;subject:string;body:string;status:string;attempts:number;error?:string};
type Inquiry={id:string;email:string;category:string;body:string;status:string};
type Coupon={code:string;percent:number;used:number;limit:number;expires:number};
type Audit={id:string;date:string;action:string;target:string;reason:string};
type Health={assets?:{scanMode:string;scanner:string;office:string;raster:string;busy:boolean};backup:{intervalMs:number;keep:number;status?:string;savedAt?:number;error?:string};database:string;orders:number;pendingNotifications:number;failedNotifications:number;metrics:{day:string;event:string;count:number}[]};
const emptyProduct:Product={id:'',name:'',category:'その他',price:0,subtitle:'',description:'',color:'263F70',sections:[],status:'draft',revision:0,version:null,fileSize:0,pageCount:0,previewCount:0,compatible:'PowerPointなどのPPTX対応ソフト',bundle:[],created:''};
export function AdminPage({onChanged}:{onChanged:()=>void}){
 const [session,setSession]=useState<Session|null>(null),[tab,setTab]=useState('products'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [nextOrders,setNextOrders]=useState<string|null>(null),[nextAudit,setNextAudit]=useState<string|null>(null);
 const [products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<Order[]>([]),[inquiries,setInquiries]=useState<Inquiry[]>([]),[notifications,setNotifications]=useState<Notification[]>([]),[coupons,setCoupons]=useState<Coupon[]>([]),[audit,setAudit]=useState<Audit[]>([]),[health,setHealth]=useState<Health|null>(null),[draft,setDraft]=useState<Product|null>(null),[search,setSearch]=useState('');
 async function reload(which=tab){if(which==='products')setProducts(await api('/api/admin/products'));if(which==='orders'){const p=await api<Page<Order>>(`/api/admin/orders?q=${encodeURIComponent(search)}`);setOrders(p.items);setNextOrders(p.nextCursor);}if(which==='inquiries')setInquiries(await api('/api/admin/inquiries'));if(which==='notifications')setNotifications(await api('/api/admin/notifications'));if(which==='coupons')setCoupons(await api('/api/admin/coupons'));if(which==='audit'){const p=await api<Page<Audit>>('/api/admin/audit');setAudit(p.items);setNextAudit(p.nextCursor);}if(which==='health')setHealth(await api('/api/admin/health'));}
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{api<Session>('/api/session').then(setSession).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(session&&session.role!=='guest')void action(()=>reload());},[session?.role,tab]);
 const logged=session&&['admin','editor'].includes(session.role);
 return <section className="inner admin"><h1>ローカル管理画面</h1><p>実際の課金・返金・メール送信はありません。</p>{error&&<p role="alert" className="alert">{error}</p>}{notice&&<p role="status" className="toast">{notice}</p>}
 {!logged?<form className="stack compact" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void action(async()=>{const r=await api<Session>('/api/admin/login','POST',Object.fromEntries(d));setSession(r);});}}><p>初回起動で生成される <code>data/admin-password.txt</code> または <code>data/editor-password.txt</code> のパスワードを使用します。</p><label>役割<select name="role"><option value="admin">運営管理者</option><option value="editor">商品管理者</option></select></label><label>管理用パスワード<input type="password" name="password" autoComplete="current-password" required/></label><label>認証コードまたは復旧コード（MFA設定済みの場合）<input name="code" autoComplete="one-time-code" maxLength={30}/></label><button className="button" disabled={busy}>管理者ログイン</button></form>:<>
 <div className="toolbar"><span>{session.role==='admin'?'運営管理者':'商品管理者'}</span><button onClick={()=>void action(async()=>{setSession(await api('/api/admin/logout','POST',{}));setDraft(null);})}>ログアウト</button></div>
 <div className="tabs" aria-label="管理メニュー">{(session.role==='editor'?['products','security']:['products','security','orders','inquiries','notifications','coupons','audit','health']).map(t=><button key={t} aria-pressed={tab===t} onClick={()=>{setTab(t);setDraft(null);}}>{{products:'商品',security:'認証設定',orders:'注文・返金',inquiries:'問い合わせ',notifications:'通知',coupons:'クーポン',audit:'操作履歴',health:'運用・分析'}[t]}</button>)}</div>
 {tab==='security'&&<AdminSecurity/>}
 {tab==='products'&&<><button onClick={()=>setDraft({...emptyProduct})}>商品を新規登録</button>{draft&&<form className="stack" onSubmit={e=>{e.preventDefault();void action(async()=>{const r=await api<Product>(draft.revision?`/api/admin/products/${draft.id}`:'/api/admin/products',draft.revision?'PATCH':'POST',draft);setDraft(r);await reload();onChanged();setNotice('商品を保存しました。');});}}><h2>{draft.revision?'商品編集':'新規商品'}</h2><label>商品ID<input required pattern="[a-zA-Z0-9-]+" maxLength={100} disabled={draft.revision>0} value={draft.id} onChange={e=>setDraft({...draft,id:e.target.value})}/></label><label>商品名<input required maxLength={100} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>説明<textarea required maxLength={2000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>カテゴリ<input required maxLength={60} value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/></label><label>税込デモ価格（円）<input type="number" min={0} max={10000000} required value={draft.price} onChange={e=>setDraft({...draft,price:Number(e.target.value)})}/></label><label>公開状態<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option value="draft">下書き</option><option value="published">公開</option><option value="stopped">販売停止</option></select></label><label>対応ソフト<input value={draft.compatible} maxLength={200} onChange={e=>setDraft({...draft,compatible:e.target.value})}/></label><fieldset><legend>セットの構成商品（任意）</legend>{products.filter(p=>p.id!==draft.id&&p.version&&!p.bundle.length).map(p=><label className="check" key={p.id}><input type="checkbox" checked={draft.bundle.includes(p.id)} onChange={e=>setDraft({...draft,bundle:e.target.checked?[...draft.bundle,p.id]:draft.bundle.filter(id=>id!==p.id)})}/>{p.name}</label>)}</fieldset><button className="button" disabled={busy}>商品を保存</button><button type="button" onClick={()=>setDraft(null)}>編集を閉じる</button>
 {draft.revision>0&&!draft.bundle.length&&draft.version&&<div className="panel"><p>ウイルス検査：{draft.scanStatus||'unscanned'} ／ プレビュー：{draft.previewMode==='image'?'スライド画像':'文字抜粋'}</p><button type="button" disabled={busy} onClick={()=>void action(async()=>{const p=await api<Product>(`/api/admin/products/${draft.id}/prepare`,'POST',{revision:draft.revision});setDraft(p);await reload();onChanged();setNotice(`ファイル処理が完了しました。検査：${p.scanStatus} ／ プレビュー：${p.previewMode==='image'?'画像':'文字抜粋'}。`);})}>画像プレビュー生成・ウイルス検査</button><small>無料ツール未導入時は未完了の状態を表示します。変換には時間がかかります。</small></div>}
 {draft.revision>0&&<label>PPTXを登録・更新（50MB以下）<input type="file" accept=".pptx" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(!file)return;void action(async()=>{if(file.size>50*1024*1024)throw new Error('50MB以下にしてください。');const base64=await new Promise<string>((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=()=>no(new Error('ファイルを読み込めません。'));r.readAsDataURL(file);});setDraft(await api(`/api/admin/products/${draft.id}/file`,'POST',{base64,revision:draft.revision}));await reload();onChanged();setNotice('PPTXを検証して登録しました。購入済みの旧版は保持されます。');});}}/><small>形式・展開サイズ・ページ数を検証します。ClamAVの状態は運用画面で確認できます。検査済み・未検査を区別します。</small></label>}</form>}
 <div className="table-scroll" tabIndex={0} role="region" aria-label="管理情報の表（横にスクロールできます）"><table><thead><tr><th>商品</th><th>価格</th><th>状態</th><th>ファイル</th><th>操作</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{p.name}<small>{p.id}</small></td><td>{yen(p.price)}</td><td>{{draft:'下書き',published:'公開',stopped:'販売停止'}[p.status]||p.status}</td><td>{p.bundle.length?`セット ${p.bundle.length}点`:`${p.pageCount}ページ`}</td><td><button onClick={()=>setDraft({...p})}>編集</button></td></tr>)}</tbody></table></div></>}
 {tab==='orders'&&<><form className="toolbar" onSubmit={e=>{e.preventDefault();void action(()=>reload());}}><label>注文検索<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="注文番号・商品名・状態"/></label><button disabled={busy}>検索</button></form>{orders.map(o=><article className="panel" key={o.id}><h2>{o.id}</h2><p>{yen(o.total)} · {o.status} · {new Date(o.date).toLocaleString('ja-JP')}</p><ul>{o.lines.map(i=><li key={i.product_id}>{i.name} · 版 {i.version?.slice(0,8)}</li>)}</ul>{o.status==='paid'&&<form className="toolbar" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);if(!window.confirm('全額模擬返金し、ダウンロード権限を停止しますか？'))return;void action(async()=>{await api('/api/admin/reauth','POST',{password:d.get('password'),code:d.get('code')});await api(`/api/admin/orders/${o.id}/refund`,'POST',{reason:d.get('reason')});await reload();onChanged();setNotice('模擬返金しました。実際のお金の移動はありません。');});}}><label>返金理由<input name="reason" required maxLength={500}/></label><label>返金確認用パスワード<input name="password" type="password" required autoComplete="current-password"/></label><label>認証コード（MFA有効時）<input name="code" autoComplete="one-time-code" maxLength={30}/></label><button disabled={busy}>全額模擬返金</button></form>}</article>)}{nextOrders&&<button disabled={busy} onClick={()=>void action(async()=>{const p=await api<Page<Order>>(`/api/admin/orders?q=${encodeURIComponent(search)}&cursor=${encodeURIComponent(nextOrders)}`);setOrders(s=>[...s,...p.items]);setNextOrders(p.nextCursor);})}>注文をさらに表示</button>}</>}
 {tab==='inquiries'&&inquiries.map(i=><article className="panel" key={i.id}><h2>{i.category} · {i.email}</h2><p className="pre-wrap">{i.body}</p><label>対応状況<select value={i.status} disabled={busy} onChange={e=>void action(async()=>{await api(`/api/admin/inquiries/${i.id}`,'PATCH',{status:e.target.value});await reload();})}><option value="open">未対応</option><option value="handling">対応中</option><option value="closed">完了</option></select></label></article>)}
 {tab==='notifications'&&<><div className="toolbar"><button disabled={busy} onClick={()=>void action(async()=>{await api('/api/admin/notifications/run','POST',{});await reload();})}>予定通知をローカル保存</button><button disabled={busy} onClick={()=>void action(async()=>{await api('/api/admin/notifications/run','POST',{simulateFailure:true});await reload();})}>通知失敗を模擬</button><button onClick={()=>void action(()=>reload())}>再読み込み</button></div><p>5秒ごとに予定通知を保存します。外部メールは送信しません。</p>{notifications.map(n=><article className="panel" key={n.id}><h2>{n.subject}</h2><p>{n.status} · 試行 {n.attempts} 回 {n.error}</p><pre>{n.body}</pre><button disabled={busy} onClick={()=>void action(async()=>{await api(`/api/admin/notifications/${n.id}/retry`,'POST',{});await reload();})}>再処理を予約</button></article>)}</>}
 {tab==='coupons'&&<><form className="stack compact" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void action(async()=>{await api('/api/admin/coupons','POST',{code:String(d.get('code')).toUpperCase(),percent:Number(d.get('percent')),limit:Number(d.get('limit')),expires:new Date(String(d.get('expires'))).getTime()});await reload();setNotice('クーポンを登録しました。');});}}><label>コード<input name="code" required pattern="[A-Za-z0-9-]{3,30}"/></label><label>割引率（%）<input name="percent" type="number" min={1} max={100} required/></label><label>利用上限<input name="limit" type="number" min={1} max={100000} required/></label><label>有効期限<input name="expires" type="datetime-local" required/></label><button className="button" disabled={busy}>クーポン登録</button></form>{coupons.map(c=><p key={c.code}>{c.code}：{c.percent}%割引 · {c.used}/{c.limit}回</p>)}</>}
 {tab==='audit'&&<><div className="table-scroll" tabIndex={0} role="region" aria-label="管理情報の表（横にスクロールできます）"><table><thead><tr><th>日時</th><th>操作</th><th>対象・理由</th></tr></thead><tbody>{audit.map(a=><tr key={a.id}><td>{new Date(a.date).toLocaleString('ja-JP')}</td><td>{a.action}</td><td>{a.target}<br/>{a.reason}</td></tr>)}</tbody></table></div>{nextAudit&&<button disabled={busy} onClick={()=>void action(async()=>{const p=await api<Page<Audit>>(`/api/admin/audit?cursor=${encodeURIComponent(nextAudit)}`);setAudit(s=>[...s,...p.items]);setNextAudit(p.nextCursor);})}>操作履歴をさらに表示</button>}</>}
 {tab==='health'&&health&&<><h2>運用状況</h2><p>ファイル検査モード：{health.assets?.scanMode} ／ ClamAV：{health.assets?.scanner} ／ LibreOffice：{health.assets?.office} ／ pdftoppm：{health.assets?.raster}</p><p>ClamAVの導入状態と、各ファイルの検査完了は別です。定義ファイルの更新は運営者が行います。</p><p>DB：{health.database} ／ 注文：{health.orders}件 ／ 通知待ち：{health.pendingNotifications}件 ／ 通知失敗：{health.failedNotifications}件</p><p>バックアップ：<code>npm run backup</code> ／ 復元はサーバー停止後に <code>npm run restore -- バックアップ名</code>。詳細はREADMEを参照してください。</p><h2>自動バックアップ</h2><p>{health.backup.intervalMs?`${health.backup.intervalMs/3600000}時間ごと・最新${health.backup.keep}件を保持`:'無効'} ／ 状態：{health.backup.status||'未実行'}</p>{health.backup.savedAt&&<p>最終成功：{new Date(health.backup.savedAt).toLocaleString('ja-JP')}</p>}{health.backup.error&&<p className="alert">{health.backup.error}</p>}<h2>購入経路の集計</h2><div className="table-scroll" tabIndex={0} role="region" aria-label="管理情報の表（横にスクロールできます）"><table><thead><tr><th>日付（UTC）</th><th>イベント</th><th>回数</th></tr></thead><tbody>{health.metrics.map(m=><tr key={m.day+m.event}><td>{m.day}</td><td>{m.event}</td><td>{m.count}</td></tr>)}</tbody></table></div><p>イベントの回数です。ユニーク人数や厳密な転換率ではありません。</p></>}
 </>}
 </section>;
}
