import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import seed from './products.json';
import {api, initialize, metric, type Product, type Order, type Quote,type Page,type Purchases} from './api';
import {AdminPage, ContactPage, LegalPage} from './LocalPages';
import './style.css';

type Store = {cart:string[]; orders:Order[]};
const KEY = 'slide-market-demo-v1';
const validId = (id:unknown): id is string => typeof id==='string' && /^[a-zA-Z0-9-]{1,100}$/.test(id);
function load():Store {
  try {
    const data = JSON.parse(localStorage.getItem(KEY) || '{}');
    return {cart:Array.isArray(data.cart)? [...new Set<string>(data.cart.filter(validId))]:[],orders:[]};
  } catch {return {cart:[],orders:[]};}
}
const yen = (n:number)=>`¥${n.toLocaleString('ja-JP')}`;
function App(){
 const [products,setProducts]=useState<Product[]>(seed.map(p=>({...p,status:'published',revision:1,version:null,fileSize:0,pageCount:4,previewCount:4,compatible:'PowerPointなどのPPTX対応ソフト',bundle:[],created:''})));
 const [favorites,setFavorites]=useState<string[]>([]),[onlyFavorites,setOnlyFavorites]=useState(false),[sort,setSort]=useState('default');
 const [quote,setQuote]=useState<Quote|null>(null),[coupon,setCoupon]=useState(''),[couponApplied,setCouponApplied]=useState(''),[accepted,setAccepted]=useState(false),[ready,setReady]=useState(false);
 const [nextHistory,setNextHistory]=useState<string|null>(null),[historyBusy,setHistoryBusy]=useState(false),[orderLoading,setOrderLoading]=useState(false);
 const [selectedOrder,setSelectedOrder]=useState<Order|null>(null);
 const [purchases,setPurchases]=useState<Purchases>({});
 const [refresh,setRefresh]=useState(0);
 const currentRoute=()=>location.hash.slice(1)||(location.pathname.startsWith('/products/')?'product/'+location.pathname.split('/')[2]:'home');
 const [store,setStore]=useState<Store>(load);
 const [route,setRoute]=useState(currentRoute);
 const [query,setQuery]=useState(''); const [category,setCategory]=useState('すべて');
 const [notice,setNotice]=useState(''); const [failure,setFailure]=useState(false); const [error,setError]=useState('');
 const [storageError,setStorageError]=useState(false);
 const [paying,setPaying]=useState(false); const requestKey=useRef<string | null>(null);
 useEffect(()=>{let active=true;initialize().then(async()=>{const data=await Promise.all([api<Product[]>('/api/products'),api<Page<Order>>('/api/orders'),api<string[]>('/api/favorites'),api<Purchases>('/api/purchases')]);if(active){setProducts(data[0]);setStore(s=>({...s,orders:data[1].items}));setNextHistory(data[1].nextCursor);setFavorites(data[2]);setPurchases(data[3]);setReady(true);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[refresh]);
 useEffect(()=>{if(!ready||route!=='checkout')return;let active=true;setQuote(null);setAccepted(false);requestKey.current=null;api<Quote>('/api/quotes','POST',{items:store.cart,coupon:couponApplied}).then(q=>{if(active)setQuote(q);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[ready,route,store.cart.join(','),couponApplied,refresh]);
 useEffect(()=>{if(route==='home'||route.startsWith('product/'))metric('view');if(route==='checkout')metric('checkout');},[route]);
 useEffect(()=>{const id=route.split('/')[1],p=products.find(p=>p.id===id);document.title=p&&route.startsWith('product/')?`${p.name} | Slide Market`:'Slide Market';let meta=document.querySelector<HTMLMetaElement>('meta[name="description"]');if(!meta){meta=document.createElement('meta');meta.name='description';document.head.append(meta);}meta.content=p?.description||'PowerPoint資料の購入とダウンロードを体験するローカルデモ';},[route,products]);
 useEffect(()=>{if(!ready||!route.startsWith('order/'))return;let active=true;setOrderLoading(true);api<Order>('/api/orders/'+route.split('/')[1]).then(o=>{if(active)setSelectedOrder(o);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setOrderLoading(false);});return()=>{active=false;};},[ready,route,refresh]);
 async function moreHistory(){if(!nextHistory||historyBusy)return;setHistoryBusy(true);try{const p=await api<Page<Order>>('/api/orders?cursor='+encodeURIComponent(nextHistory));setStore(s=>({...s,orders:[...s.orders,...p.items.filter(o=>!s.orders.some(x=>x.id===o.id))]}));setNextHistory(p.nextCursor);}catch(e){setError((e as Error).message);}finally{setHistoryBusy(false);}}
 const purchaseFor=(p:Product)=>purchases[p.id]||(p.bundle.length?p.bundle.map(id=>purchases[id]).find(Boolean):undefined);
 const changed=()=>setRefresh(n=>n+1);
 const toggleFavorite=async(id:string)=>{try{await api('/api/favorites'+(favorites.includes(id)?'/'+id:''),favorites.includes(id)?'DELETE':'POST',favorites.includes(id)?undefined:{productId:id});setFavorites(await api('/api/favorites'));}catch(e){setError((e as Error).message);}};
 const heading=useRef<HTMLElement>(null); const previousRoute=useRef(route); const paymentLock=useRef(false);
 useEffect(()=>{try {localStorage.setItem(KEY,JSON.stringify({cart:store.cart}));setStorageError(false);}catch{setStorageError(true);}},[store]);
 useEffect(()=>{const handle=()=>{setRoute(currentRoute());setError('');setNotice('');setFailure(false);};window.addEventListener('hashchange',handle);return()=>window.removeEventListener('hashchange',handle);},[]);
 useEffect(()=>{if(previousRoute.current===route)return;previousRoute.current=route;heading.current?.focus();window.scrollTo(0,0);},[route]);
 const cart=products.filter(p=>store.cart.includes(p.id)); const total=quote&&route==='checkout'?quote.total:cart.reduce((s,p)=>s+p.price,0);
 const add=(id:string)=>{const p=products.find(p=>p.id===id),owned=p&&purchaseFor(p);if(owned){location.hash='order/'+owned.orderId;return;}metric('cart');requestKey.current=null;setStore(s=>({...s,cart:[...new Set([...s.cart,id])]}));setNotice('カートに追加しました。');};
 const remove=(id:string)=>{requestKey.current=null;setStore(s=>({...s,cart:s.cart.filter(x=>x!==id)}));};
 const pay=async()=>{
  if(!cart.length||paymentLock.current||!quote||!accepted)return;
  if(quote.expires<=Date.now()){setError('見積もりが失効しました。購入確認をやり直してください。');setQuote(null);return;}
  paymentLock.current=true;setPaying(true);setError('');
  requestKey.current??=crypto.randomUUID();
  try {
   const order=await api<Order>('/api/orders','POST',{quoteId:quote.id,result:failure?'failure':'success',accepted:true,termsVersion:quote.terms},requestKey.current);
   setStore(s=>({cart:[],orders:[order,...s.orders.filter(o=>o.id!==order.id)]}));setPurchases(p=>({...p,...Object.fromEntries(order.lines.map(i=>[i.product_id,{orderId:order.id,name:i.name}]))}));requestKey.current=null;location.hash=`order/${order.id}`;
  }catch(e){setError(e instanceof Error?e.message:'通信に失敗しました。再試行してください。');}
  finally{paymentLock.current=false;setPaying(false);}
 };
 const reset=async()=>{
  if(!window.confirm('カートとデモ注文履歴を削除しますか？'))return;
  try{await api('/api/orders','DELETE');setStore({cart:[],orders:[]});setPurchases({});setNextHistory(null);requestKey.current=null;setNotice('デモデータをリセットしました。');}
  catch{setError('リセットできませんでした。再度お試しください。');}
 };
 const [page,id]=route.split('/');const product=products.find(p=>p.id===id);const order=selectedOrder?.id===id?selectedOrder:store.orders.find(o=>o.id===id);
 const visible=products.filter(p=>(!onlyFavorites||favorites.includes(p.id))&&(category==='すべて'||p.category===category)&&`${p.name} ${p.description} ${p.category}`.includes(query.trim())).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:sort==='new'?b.created.localeCompare(a.created):0);
 const title=page==='home'?'資料を探す':page==='product'?product?.name:page==='cart'?'カート':page==='checkout'?'デモ決済':page==='order'?'注文完了':page==='history'?'デモ注文履歴':page==='guide'?'ご利用ガイド':'ページが見つかりません';
 const preview=(p:Product)=><img src={`/api/products/${p.id}/previews/0`} alt={`${p.name}の表紙プレビュー`} width="1280" height="720"/>;
 const downloads=(o:Order)=><div className="downloads"><p>合計：{yen(o.total)} · {o.status==='refunded'?'模擬返金済み': '模擬決済済み'}</p>{o.lines.map(line=><div className="download-row" key={line.product_id}><div><strong>{line.name}</strong><span>PowerPoint · 購入時のファイル版 {line.version?.slice(0,8)}</span></div>{o.status==='paid'?<a className="button" href="#history" onClick={async e=>{e.preventDefault();try{const link=await api<{url:string}>(`/api/orders/${o.id}/download-links/${line.product_id}`,'POST',{});const a=document.createElement('a');a.href=link.url;a.download=line.name+'.pptx';document.body.append(a);a.click();a.remove();}catch(e){setError((e as Error).message);}}}>ダウンロード ↓</a>:<span>ダウンロード権限は停止されています。</span>}</div>)}{o.receiptSnapshot&&<p><a className="text-link" href={`/api/orders/${o.id}/receipt`} target="_blank" rel="noopener noreferrer">模擬領収書を表示・印刷</a> · <a className="text-link" href={`/api/orders/${o.id}/receipt?download=1`} download>HTMLを保存</a></p>}</div>;
 return <><a className="skip" href="#content" onClick={e=>{e.preventDefault();heading.current?.focus();}}>本文へ移動</a>
 <div className="demo-bar">学習用デモ <span>実際の請求はありません。表示価格はサンプルです。</span></div>
 <header><a className="brand" href="#home"><span className="brand-icon">S<span>↗</span></span>Slide Market<span className="brand-dot">.</span></a><nav aria-label="メインナビゲーション"><a href="#home" aria-current={page==='home'?'page':undefined}>資料を探す</a><a href="#guide">ガイド</a><a className="cart-link" href="#cart">カート <span>{cart.length}</span></a></nav></header>
 <main id="content" ref={heading} tabIndex={-1}>
 {storageError&&<p role="alert" className="alert">ブラウザに保存できません。この画面を閉じるとデータが失われる場合があります。</p>}
 {error&&page!=='checkout'&&<p role="alert" className="alert">{error}</p>}
 <div role="status" className={notice?'toast':'sr-only'}>{notice}</div>
 {page==='admin'?<AdminPage onChanged={changed}/>:page==='contact'?<ContactPage/>:page==='legal'?<LegalPage kind={id}/>:page==='home'?<>
 <section className="hero"><div className="hero-copy"><p className="eyebrow">MAKE YOUR IDEAS SHINE</p><h1>アイデアを、<br/>伝わる資料に<span>。</span></h1><p>企画も、報告も、学びも。<br/>あなたの次の一歩を支える、スライドを見つけよう。</p><a className="button" href="#catalog" onClick={e=>{e.preventDefault();document.getElementById('catalog')?.scrollIntoView({behavior:'smooth'});}}>資料を見つける <span>↗</span></a><div className="hero-tags"><span>編集できるPPTX</span><span>ダウンロード体験</span><span>登録不要</span></div></div><div className="hero-art" aria-hidden="true"><div className="art-grid"/><div className="mini-slide back"><span>YOUR NEXT IDEA</span><div className="bars"><i/><i/><i/></div></div><div className="mini-slide front"><span>SLIDE MARKET</span><strong>伝える、<br/>その先へ。</strong><div className="slide-line"/><small>Presentation collection — 01</small></div><div className="art-note">小さなアイデアから、大きな一歩へ。</div></div></section>
 <section className="catalog" id="catalog"><div className="section-head"><div><p className="eyebrow">THE COLLECTION</p><h2>あなたに合う資料を。</h2></div><span>{visible.length} 件のサンプル資料</span></div><div className="toolbar"><label>並び替え<select value={sort} onChange={e=>setSort(e.target.value)}><option value="default">標準</option><option value="low">価格が安い順</option><option value="high">価格が高い順</option><option value="new">新着順</option></select></label><label className="check"><input type="checkbox" checked={onlyFavorites} onChange={e=>setOnlyFavorites(e.target.checked)}/>お気に入りだけ</label></div><div className="filters"><div className="categories" aria-label="カテゴリ">{['すべて',...new Set(products.map(p=>p.category))].map(c=><button key={c} aria-pressed={c===category} className={c===category?'selected':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><label className="search"><span className="sr-only">資料を検索</span><span aria-hidden="true">⌕</span><input type="search" placeholder="資料を検索" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 {visible.length?<div className="product-grid">{visible.map(p=><article className="card" key={p.id}><a href={`/products/${p.id}`} className="image-link">{preview(p)}<span className="image-label">PPTX · {p.pageCount || "SET"} PAGES</span></a><div className="card-body"><div className="toolbar"><span className="category">{p.category}</span><button className="favorite" aria-label={`${p.name}をお気に入り${favorites.includes(p.id)?'から削除':'に追加'}`} aria-pressed={favorites.includes(p.id)} onClick={()=>void toggleFavorite(p.id)}>{favorites.includes(p.id)?'★':'☆'}</button></div><h3><a href={`/products/${p.id}`}>{p.name}</a></h3><p>{p.description}</p><div className="card-bottom"><strong>{yen(p.price)}<small> デモ価格</small></strong>{purchaseFor(p)?<a className="text-link" href={`#order/${purchaseFor(p)!.orderId}`}>購入済み・再取得</a>:<button className="add-button" onClick={()=>add(p.id)} disabled={store.cart.includes(p.id)} aria-label={`${p.name}をカートに追加`}>{store.cart.includes(p.id)?'追加済み':'＋'}</button>}</div></div></article>)}</div>:<div className="empty"><h3>該当する資料がありません</h3><p>検索キーワードやカテゴリを変更してください。</p><button onClick={()=>{setQuery('');setCategory('すべて');setOnlyFavorites(false);}}>条件をリセット</button></div>}</section>
 <section className="how"><div><p className="eyebrow">HOW IT WORKS</p><h2>見つけて、試して、<br/>ダウンロード。</h2></div><ol><li><b>01</b><strong>資料を選ぶ</strong><p>用途に合う資料をカートへ。</p></li><li><b>02</b><strong>デモ購入を体験</strong><p>カード情報の入力は不要です。</p></li><li><b>03</b><strong>資料をダウンロード</strong><p>サンプルを自由に編集してみよう。</p></li></ol></section></>:
 <section className="inner"><a className="back-link" href="#home">← 資料一覧へ</a><p className="eyebrow">SLIDE MARKET / DEMO</p><h1>{title||'ページが見つかりません'}</h1>
 {page==='product'&&product?<div className="detail"><div>{preview(product)}<h2>{product.previewMode==='image'?'スライドの画像プレビュー':'内容のテキストプレビュー'}</h2><p>{product.previewMode==='image'?'PPTXから変換した画像です。フォントや表示はPowerPointと異なる場合があります。セットでは先頭商品のプレビューを表示します。':'スライド内の文字を抜粋した画像です。実際のレイアウトとは異なります。'}</p><div className="preview-grid">{Array.from({length:Math.min(product.previewCount,12)},(_,i)=><img key={i} src={`/api/products/${product.id}/previews/${i}`} alt={`${product.name}の${i+1}ページ目のプレビュー`} loading="lazy"/>)}</div><h2>収録内容</h2><ol className="contents"><li>表紙：{product.name}</li>{product.sections.map(s=><li key={s}>{s}</li>)}</ol><p>セット商品は構成商品のファイルをまとめて提供します。</p></div><div className="detail-info"><span className="category">{product.category}</span><h2>{product.subtitle}</h2><p>{product.description}</p><dl><div><dt>形式</dt><dd>PowerPoint（.pptx）</dd></div><div><dt>ページ数</dt><dd>{product.bundle.length?`セット ${product.bundle.length}商品`: `${product.pageCount}ページ`}</dd></div><div><dt>必要ソフト</dt><dd>{product.compatible}</dd></div><div><dt>ファイルサイズ</dt><dd>{(product.fileSize/1024).toFixed(1)} KB</dd></div></dl><p className="price">{yen(product.price)}<small> デモ価格・請求なし</small></p>{purchaseFor(product)?<a className="button full" href={`#order/${purchaseFor(product)!.orderId}`}>購入済み資料を再ダウンロード</a>:<button className="button full" disabled={store.cart.includes(product.id)} onClick={()=>add(product.id)}>{store.cart.includes(product.id)?'カートに追加済み':'カートに追加する'}</button>}<a className="text-link" href="#cart">カートを見る →</a><h3>利用条件</h3><p>自作サンプルです。学習・編集・商用利用ができます。元ファイルの再販売・再配布は禁止します。実販売用の完成資料ではありません。</p></div></div>:
 page==='cart'||page==='checkout'?<><p className="demo-note">模擬決済です。実際の請求はなく、カード情報や個人情報の入力も不要です。</p>{cart.length?<div className="checkout-layout"><div className="cart-items">{cart.map(p=><div className="cart-row" key={p.id}>{preview(p)}<div><a href={`/products/${p.id}`}><strong>{p.name}</strong></a><p>PPTX · {p.bundle.length?`${p.bundle.length}商品セット`:`${p.pageCount}ページ`} · 数量1</p>{purchaseFor(p)&&<a className="text-link" href={`#order/${purchaseFor(p)!.orderId}`}>購入済みです。再ダウンロードへ</a>}<button className="text-button" onClick={()=>remove(p.id)} aria-label={`${p.name}を削除`}>削除</button></div><strong>{yen(p.price)}</strong></div>)}</div><aside className="summary"><h2>注文内容</h2><div><span>商品数</span><strong>{cart.length}点</strong></div><div className="total"><span>合計（デモ価格）</span><strong>{yen(total)}</strong></div><p>デジタル資料のため配送はありません。実際の請求はありません。</p>{page==='cart'?<a className="button full" href="#checkout">デモ購入へ進む →</a>:<><fieldset><legend>模擬決済の結果</legend><label><input type="radio" name="result" checked={!failure} onChange={()=>{setFailure(false);setError('');requestKey.current=null;}}/> 成功</label><label><input type="radio" name="result" checked={failure} onChange={()=>{setFailure(true);requestKey.current=null;}}/> 失敗を試す</label></fieldset><form className="stack" onSubmit={e=>{e.preventDefault();setError('');setCouponApplied(coupon.trim());setRefresh(n=>n+1);}}><label>クーポン（任意）<input value={coupon} maxLength={30} onChange={e=>setCoupon(e.target.value)}/></label><button type="submit">見積もりを更新</button></form>{quote?<p>割引：{yen(quote.discount)} ／ 見積もり期限：{new Date(quote.expires).toLocaleTimeString('ja-JP')}</p>:<p role="status">見積もりを確認してください。</p>}<label className="check"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span><a href="#legal/terms">利用規約・利用許諾</a>と<a href="#legal/refund">返金条件</a>を確認して同意する</span></label>{error&&<p role="alert" className="alert">{error}</p>}<button className="button full" onClick={pay} disabled={paying||!quote||!accepted}>デモ購入を確定する</button><a href="#cart" className="text-link">カートに戻る</a></>}</aside></div>:<div className="empty"><h2>カートは空です</h2><p>気になる資料を追加して、デモ購入を体験してください。</p><a className="button" href="#home">資料を探す</a></div>}</>:
 page==='order'&&orderLoading?<p role="status">注文を確認しています。</p>:page==='order'&&order?<><div className="success"><span>✓</span><h2>{order.status==='refunded'?'デモ注文は返金済みです。':'デモ購入が完了しました。'}</h2><p>実際の請求はありません。サンプル資料をダウンロードしてみましょう。</p></div><p className="order-id">注文番号：{order.id}<br/>注文日時：{new Date(order.date).toLocaleString('ja-JP')}</p>{downloads(order)}{order.licenseSnapshot&&<details className="panel"><summary>購入時に同意した利用規約・返金条件</summary><p>版：{order.licenseSnapshot.version}</p>{[order.licenseSnapshot.terms,order.licenseSnapshot.refund].map(p=><div key={p.title}><h3>{p.title}</h3>{p.body.map(t=><p key={t}>{t}</p>)}</div>)}</details>}<p className="demo-note">このブラウザのデモ注文をサーバーで確認してファイルを配信します。実際の入金を確認する仕組みではありません。</p><a href="#history" className="text-link">デモ注文履歴を見る →</a></>:
 page==='history'?<>{store.orders.length?store.orders.map(o=><article className="history" key={o.id}><p className="order-id">{new Date(o.date).toLocaleString('ja-JP')} · {o.id}</p>{downloads(o)}</article>):<div className="empty"><h2>デモ注文はまだありません</h2><a className="button" href="#home">資料を探す</a></div>}{nextHistory&&<button className="button" disabled={historyBusy} onClick={()=>void moreHistory()}>注文履歴をさらに表示</button>}</>:
 page==='guide'?<div className="guide"><h2>購入とダウンロード</h2><p>資料をカートに追加し、デモ決済で「成功」を選んで確定すると、注文完了画面からPPTXファイルを取得できます。「失敗を試す」で再試行の流れも確認できます。</p><h2>資料について</h2><p>各資料は表紙と3ページの、自作の短い学習用サンプルです。PPTX対応のPowerPointなどで開いて編集できます。表示価格は架空で、実際の請求はありません。</p><h2>利用条件</h2><p>サンプルの学習・編集・商用利用を許可します。元ファイルの再販売・再配布は禁止します。第三者の素材は使用していません。</p><h2>保存とデモの制約</h2><p>カートはブラウザ、注文はサーバーのSQLiteに保存されます。このブラウザのCookieで注文を確認するため、別の端末には引き継がれません。問い合わせには架空のメールを使用してください。カード情報は収集しません。実際の販売には購入者認証と入金確認が必要です。</p><a className="text-link" href="#history">デモ注文履歴を見る →</a><h2>データのリセット</h2><p>このブラウザのカートとデモ注文履歴を削除します。</p><button className="reset" onClick={reset}>デモデータをリセット</button></div>:<div className="empty"><p>指定された商品や注文は見つかりません。</p><a className="button" href="#home">資料を探す</a></div>}
 </section>}
 </main><footer><div><a className="brand" href="#home">Slide Market.</a><p>アイデアを、伝わる資料に。</p></div><div><a href="#guide">ご利用ガイド</a><a href="#history">デモ注文履歴</a><a href="#contact">お問い合わせ</a><a href="#legal/terms">利用規約</a><a href="#legal/privacy">プライバシー</a><a href="#legal/commerce">特商法表記</a><a href="#legal/refund">返金条件</a><a href="#admin">ローカル管理</a><small>学習用デモ / 実際の販売・請求は行いません。</small></div></footer></>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
